;;; gnucobol.el -- summary

;; Author:   Wade Mealing
;; Version   0.0.1
;; Created:  28 Aug 2022.
;; Keywords: languages cobol

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;; Code:


(defvar gnucobol-mode-hook nil "A major mode for GnuCOBOL.")

(defvar cobol-tab-width 4 "Width of a tab for `cobol-mode'.")

(defconst cobol-directives
  '("CALL-CONVENTION"
    "D"
    "DEFINE"
    "ELIF"
    "ELSE"
    "END-EVALUATE"
    "END-IF"
    "EVALUATE"
    "FLAG-02"
    "FLAG-85"
    "FLAG-NATIVE-ARITHMETIC"
    "IF"
    "IMP"
    "LEAP-SECOND"
    "LISTING"
    "PAGE"
    "PROPAGATE"
    "SOURCE"
    "TURN"
    "WHEN")
  "List of COBOL compiler directives.")

(defconst cobol-verbs-74
  '("GO TO"
    "NEXT SENTENCE"
    "ACCEPT"
    "ADD"
    "ALTER"
    "CALL"
    "CANCEL"
    "CLOSE"
    "COPY"
    "COMPUTE"
    "DELETE"
    "DISABLE"
    "DISPLAY"
    "DIVIDE"
    "ENABLE"
    "ENTER"
    "EXIT"
    "GENERATE"
    "GO"
    "IF"
    "INITIATE"
    "INSPECT"
    "MERGE"
    "MOVE"
    "MULTIPLY"
    "OPEN"
    "PERFORM"
    "READ"
    "RECEIVE"
    "RELEASE"
    "RESET"
    "RETURN"
    "REWRITE"
    "SEARCH"
    "SELECT"
    "SEND"
    "SET"
    "SORT"
    "START"
    "STOP"
    "STRING"
    "SUBTRACT"
    "SUPPRESS"
    "TERMINATE"
    "UNSTRING"
    "USE"
    "WRITE"))

(defconst cobol-verbs-85
  (append cobol-verbs-74
          '("CONTINUE"
            "EVALUATE"
            "INITIALIZE"
            "REPLACE")))

(defconst cobol-removed-verbs-2002
  '("ALTER" "ENTER"))

(defconst cobol-verbs-2002
  (append (cobol--remove-strings cobol-verbs-85 cobol-removed-verbs-2002)
          '("ALLOCATE"
            "FREE"
            "GOBACK"
            "INVOKE"
            "RAISE"
            "RESUME"
            "UNLOCK"
            "VALIDATE")))

(defconst cobol-removed-verbs-2014
  '("DISABLE"
    "ENABLE"
    "SEND"
    "RECEIVE"))

(defconst cobol-verbs-2014
  (cobol--remove-strings cobol-verbs-2002
                         cobol-removed-verbs-2014))

(defconst cobol-verbs-extensions
  '("DELETE FILE"
    "READY TRACE"
    "RESET TRACE"
    "XML GENERATE"
    "XML PARSE"
    "ATTACH"
    "ALLOW" ; Unisys COBOL-74
    "AWAIT-OPEN" ; Unisys COBOL-74
    "CAUSE" ; Unisys COBOL-74
    "CHAIN"
    "CHANGE" ; Unisys COBOL-74
    "COLOR"
    "COMMIT"
    "CREATE"
    "DECLARE"
    "DELEGATE"
    "DETACH"
    "DISALLOW" ; Unisys COBOL-74
    "ENTRY"
    "EXAMINE"
    "EXEC"
    "EXECUTE"
    "EXHIBIT"
    ;; "LOCK" ; Unisys COBOL-74 ; Treated as keyword
    "MODIFY"
    "NOTE"
    "ON" ; OS/VS Statement ; Keyword <= COBOL-74
    "PROCESS" ; Unisys COBOL-74
    "RESPOND" ; Unisys COBOL-74
    "ROLLBACK"
    ;; "RUN" ; Unisys COBOL-74 ; Treated as keyword
    "SEEK" ; Unisys COBOL-74
    "SERVICE"
    "SYNC" ; <= COBOL-74
    "TRANSFORM"
    "TRY"
    "WAIT"))

(defconst cobol-verbs
  (append cobol-verbs-2014
          cobol-removed-verbs-2002
          cobol-removed-verbs-2014
          cobol-verbs-extensions)
  "List of COBOL verb keywords.")

(defconst cobol-scope-terminators-85
  '("END-ADD"
    "END-CALL"
    "END-COMPUTE"
    "END-DELETE"
    "END-DIVIDE"
    "END-EVALUATE"
    "END-IF"
    "END-MULTIPLY"
    "END-PERFORM"
    "END-READ"
    "END-RECEIVE"
    "END-RETURN"
    "END-REWRITE"
    "END-SEARCH"
    "END-START"
    "END-STRING"
    "END-SUBTRACT"
    "END-UNSTRING"
    "END-WRITE"))

(defconst cobol-scope-terminators-2002
  (append cobol-scope-terminators-85
          '("END-ACCEPT"
            "END-DISPLAY")))

(defconst cobol-removed-scope-terminators-2014
  '("END-RECEIVE"))

(defconst cobol-scope-terminators-2014
  (cobol--remove-strings cobol-scope-terminators-2002
                         cobol-removed-scope-terminators-2014))

(defconst cobol-scope-terminators-xml-tr
  '("END-OPEN"))

(defconst cobol-scope-terminators-extensions
  '("END-CHAIN"
    "END-COLOR"
    "END-DELEGATE"
    "END-EXEC"
    "END-INVOKE"
    "END-MODIFY"
    "END-MOVE"
    "END-SYNC"
    "END-TRY"
    "END-WAIT"
    "END-XML"))

(defconst cobol-scope-terminators
  (append cobol-scope-terminators-2014
          cobol-scope-terminators-xml-tr
          cobol-scope-terminators-extensions))

(defconst cobol-keywords-74
  '("ACCESS"
    "ADVANCING"
    "AFTER"
    "ALL"
    "ALPHABETIC"
    "ALSO"
    "ALTERNATE"
    "AND"
    "ARE"
    "AREA"
    "AREAS"
    "ASCENDING"
    "ASSIGN"
    "AT"
    "AUTHOR"
    "BEFORE"
    "BLANK"
    "BLOCK"
    "BOTTOM"
    "BY"
    "CD"
    "CF"
    "CH"
    "CHARACTER"
    "CHARACTERS"
    "CLOCK-UNITS"
    "COBOL"
    "CODE"
    "CODE-SET"
    "COLLATING"
    "COLUMN"
    "COMMA"
    "COMMUNICATION"
    "COMP"
    "COMPUTATIONAL"
    "CONFIGURATION"
    "CONTAINS"
    "CONTROL"
    "CONTROLS"
    "CORR"
    "CORRESPONDING"
    "COUNT"
    "CURRENCY"
    "DATA"
    "DATE"
    "DATE-COMPILED"
    "DATE-WRITTEN"
    "DAY"
    "DE"
    "DEBUG-CONTENTS"
    "DEBUG-ITEM"
    "DEBUG-LINE"
    "DEBUG-NAME"
    "DEBUG-SUB-1"
    "DEBUG-SUB-2"
    "DEBUG-SUB-3"
    "DEBUGGING"
    "DECIMAL-POINT"
    "DECLARATIVES"
    "ENVIRONMENT"
    "DELIMITED"
    "DELIMITER"
    "DEPENDING"
    "DESCENDING"
    "DESTINATION"
    "DETAIL"
    "DIVISION"
    "DOWN"
    "DUPLICATES"
    "DYNAMIC"
    "EGI"
    "ELSE"
    "EMI"
    "END"
    "END-OF-PAGE"
    "EOP"
    "EQUAL"
    "ERROR"
    "ESI"
    "EVERY"
    "EXCEPTION"
    "EXTEND"
    "FD"
    "FILE"
    "FILE-CONTROL"
    "FILLER"
    "FINAL"
    "FIRST"
    "FOOTING"
    "FOR"
    "FROM"
    "GIVING"
    "GREATER"
    "GROUP"
    "HEADING"
    "I-O"
    "I-O-CONTROL"
    "IDENTIFICATION"
    "INDEX"
    "INDEXED"
    "IN"
    "INDICATE"
    "INITIAL"
    "INPUT"
    "INPUT-OUTPUT"
    "INSTALLATION"
    "INTO"
    "INVALID"
    "IS"
    "JUST"
    "JUSTIFIED"
    "KEY"
    "LABEL"
    "LAST"
    "LEADING"
    "LEFT"
                                        ; LENGTH is treated as an intrinsic function.
    "LESS"
    "LIMIT"
    "LIMITS"
    "LINAGE"
    "LINAGE-COUNTER"
    "LINE"
    "LINE-COUNTER"
    "LINES"
    "LINKAGE"
    "LOCK"
    "NEXT"
    "MEMORY"
    "MESSAGE"
    "MODE"
    "MODULES"
    "MULTIPLE"
    "NATIVE"
    "NEGATIVE"
    "NO"
    "NOT"
    "NUMBER"
    "NUMERIC"
    "OBJECT-COMPUTER"
    "OCCURS"
    "OF"
    "OFF"
    "OMITTED"
    ;; "ON" ; OS/VS Statement ; Keyword <= COBOL-74
    "OPTIONAL"
    "OR"
    "ORGANIZATION"
    "OUTPUT"
    "OVERFLOW"
    "PAGE"
    "PAGE-COUNTER"
    "PF"
    "PH"
    "PIC"
    "PICTURE"
    "PLUS"
    "POINTER"
    "POSITION"
    "POSITIVE"
    "PRINTING"
    "PROCEDURE"
    "PROCEDURES"
    "PROCEED"
    "PROGRAM"
    "PROGRAM-ID"
    "QUEUE"
    "RANDOM"
    "RD"
    "RECORD"
    "RECORDS"
    "REDEFINES"
    "REEL"
    "REFERENCES"
    "RELATIVE"
    "REMAINDER"
    "REMOVAL"
    "RENAMES"
    "REPLACING"
    "REPORT"
    "REPORTING"
    "REPORT"
    "RERUN"
    "RESERVE"
    "REVERSED"
    "REWIND"
    "RF"
    "RH"
    "RIGHT"
    "ROUNDED"
    "RUN"
    "SAME"
    "SD"
    "SECTION"
    "SECURITY"
    "SEGMENT"
    "SEGMENT-LIMIT"
    "SEND"
    "SENTENCE"
    "SEPARATE"
    "SEQUENCE"
    "SEQUENTIAL"
    "SIZE"
    "SORT-MERGE"
    "SOURCE"
    "SOURCE-COMPUTER"
    "SPECIAL-NAMES"
    "STANDARD"
    "STANDARD-1"
    "STATUS"
    "SUB-QUEUE-1"
    "SUB-QUEUE-2"
    "SUB-QUEUE-3"
    "SYMBOLIC"
    "SYNCHRONIZED"
    "TABLE"
    "TALLYING"
    "TAPE"
    "TERMINAL"
    "TEXT"
    "THAN"
    "THROUGH"
    "THRU"
    "TIME"
    "TIMES"
    "TO"
    "TOP"
    "TRAILING"
    "TYPE"
    "UNIT"
    "UNTIL"
    "UP"
    "UPON"
    "USAGE"
    "USING"
    "VALUE"
    "VALUES"
    "VARYING"
    "WHEN"
    "WITH"
    "WORDS"
    "WORKING-STORAGE"))

(defconst cobol-keywords-85
  (append cobol-keywords-74
          '("ALPHABET"
            "ALPHABETIC-LOWER"
            "ALPHABETIC-UPPER"
            "ALPHANUMERIC"
            "ALPHANUMERIC-EDITED"
            "ANY"
            "BINARY"
            "CLASS"
            "COMMON"
            "CONTENT"
            "CONVERTING"
            "DAY-OF-WEEK"
            "EXTERNAL"
            "FALSE"
            "FUNCTION"
            "GLOBAL"
            "NUMERIC-EDITED"
            "ORDER"
            "OTHER"
            "PACKED-DECIMAL"
            "PADDING"
            "PURGE"
            "REFERENCE"
            "STANDARD-2"
            "TEST"
            "THEN"
            "TRUE")))

(defconst cobol-removed-keywords-2002
  '("AUTHOR"
    "INSTALLATION"
    "DATE-WRITTEN"
    "DATE-COMPILED"
    "SECURITY"
    "MEMORY"
    "RERUN"
    "MULTIPLE"
    "TAPE"
    "LABEL"
    "REVERSED"
    "DEBUG-CONTENTS"
    "DEBUG-ITEM"
    "DEBUG-LINE"
    "DEBUG-NAME"
    "DEBUG-SUB-1"
    "DEBUG-SUB-2"
    "DEBUG-SUB-3"))

(defconst cobol-keywords-2002
  (append (cobol--remove-strings cobol-keywords-85
                                 cobol-removed-keywords-2002)
          '("ACTIVE-CLASS"
            "ADDRESS"
            "ALIGNED"
            "ANYCASE"
            "AS"
            "B-AND"
            "B-NOT"
            "B-OR"
            "B-XOR"
            "BASED"
            "BINARY-CHAR"
            "BINARY-DOUBLE"
            "BINARY-LONG"
            "BINARY-SHORT"
            "BIT"
            "BOOLEAN"
            "CLASS-ID"
            "COL"
            "COLS"
            "COLUMNS"
            "CONDITION"
            "CONSTANT"
            "CRT"
            "CURSOR"
            "DATA-POINTER"
            "DEFAULT"
            "EC"
            "EO"
            "EXCEPTION-OBJECT"
            "FACTORY"
            "FLOAT-EXTENDED"
            "FLOAT-LONG"
            "FLOAT-SHORT"
            "FORMAT"
            "FUNCTION-ID"
            "GET"
            "GROUP-USAGE"
            "INHERITS"
            "INTERFACE"
            "INTERFACE-ID"
            "LAST"
            "LOCAL-STORAGE"
            "LOCALE"
            "METHOD"
            "METHOD-ID"
            "MINUS"
            "NATIONAL"
            "NATIONAL-EDITED"
            "NESTED"
            "OBJECT"
            "OBJECT-REFERENCE"
            "OPTIONS"
            "OVERRIDE"
            "PRESENT"
            "PROGRAM-POINTER"
            "PROPERTY"
            "PROTOTYPE"
            "RAISING"
            "REPOSITORY"
            "RETRY"
            "RETURNING"
            "SCREEN"
            "SHARING"
            "SOURCES"
            "SYSTEM-DEFAULT"
            "TYPEDEF"
            "UNIVERSAL"
            "USER-DEFAULT"
            "VAL-STATUS"
            "VALID"
            "VALIDATE-STATUS")))

(defconst cobol-keywords-finalizer-tr
  '("AUTO-METHOD"))

(defconst cobol-keywords-xml-tr
  '("DOCUMENT"
    "IDENTIFIED"
    "VERSION-XML"))

(defconst cobol-removed-keywords-2014
  '("CD"
    "DEBUGGING"
    "EGI"
    "EMI"
    "ESI"
    "MESSAGE"
    "PADDING"
    "PURGE"
    "QUEUE"
    "SEGMENT"
    "SUB-QUEUE-1"
    "SUB-QUEUE-2"
    "SUB-QUEUE-3"
    "TERMINAL"
    "TEXT"))

(defconst cobol-keywords-2014
  (append (cobol--remove-strings cobol-keywords-2002
                                 cobol-removed-keywords-2014)
          '("FARTHEST-FROM-ZERO"
            "FLOAT-BINARY-32"
            "FLOAT-BINARY-64"
            "FLOAT-BINARY-128"
            "FLOAT-DECIMAL-16"
            "FLOAT-DECIMAL-34"
            "FLOAT-INFINITY"
            "FLOAT-NOT-A-NUMBER"
            "FLOAT-NOT-A-NUMBER-QUIET"
            "FLOAT-NOT-A-NUMBER-SIGNALING"
            "FUNCTION-POINTER"
            "IN-ARITHMETIC-RANGE"
            "NEAREST-TO-ZERO")))

(defconst cobol-keywords-extensions
  '("3-D"
    "ABSENT"
    "ABSTRACT"
    "ACQUIRE"
    "ACTION"
    "ACTIVE-X"
    "ACTUAL"
    "ACCEPT-CLOSE"
    "ACCEPT-OPEN"
    "ADDRESS-ARRAY"
    "ADDRESS-OFFSET"
    "ADJUSTABLE-COLUMNS"
    "AFP-5A"
    "ALIGNMENT"
    "ALLOWING"
    "ANY LENGTH"
    "APPLY"
    "ARGUMENT-NUMBER"
    "ARGUMENT-VALUE"
    "ASSEMBLY-ATTRIBUTES"
    "ASSOCIATED-DATA" ; Unisys
    "ASSOCIATED-DATA-LENGTH" ; Unisys
    "AUTO-DECIMAL"
    "AUTO-HYPHEN-SKIP"
    "AUTO-MINIMIZE"
    "AUTO-RESIZE"
    "AUTO-SKIP"
    "AUTO-SPIN"
    "AUTOTERMINATE"
    "AX-EVENT-LIST"
    "B-EXOR"
    "B-LEFT"
    "B-RIGHT"
    "BACKGROUND-COLOUR"
    "BACKGROUND-HIGH"
    "BACKGROUND-LOW"
    "BACKGROUND-STANDARD"
    "BACKWARD"
    "BAR"
    "BASIS"
    "BEEP"
    "BEGINNING"
    "BINARY-INT"
    "BINARY-LONG-LONG"
    "BIND"
    "BITMAP"
    "BITMAP-END"
    "BITMAP-HANDLE"
    "BITMAP-NUMBER"
    "BITMAP-RAW-HEIGHT"
    "BITMAP-RAW-WIDTH"
    "BITMAP-SCALE"
    "BITMAP-START"
    "BITMAP-TIMER"
    "BITMAP-TRAILING"
    "BITMAP-WIDTH"
    "BLINKING"
    "BLOB"
    "BLOB-FILE"
    "BLOB-LOCATOR"
    "BOLD"
    "BOX"
    "BOXED"
    "BROWSING"
    "BULK-ADDITION"
    "BUSY"
    "BUTTONS"
    "C01"
    "C02"
    "C03"
    "C04"
    "C05"
    "C06"
    "C07"
    "C08"
    "C09"
    "C10"
    "C11"
    "C12"
    "CALENDAR-FONT"
    "CALLED"
    "CANCEL-BUTTON"
    "CATCH"
    "CBL"
    "CBL-CTR"
    "CCOL"
    "CELL"
    "CELL-COLOR"
    "CELL-DATA"
    "CELL-FONT"
    "CELL-PROTECTION"
    "CELLS"
    "CENTERED"
    "CENTERED-HEADINGS"
    "CENTURY-DATE"
    "CENTURY-DAY"
    "CHAINING"
    "CHANGED"
    "CHAR-VARYING"
    "CHART"
    "CHECK-BOX"
    "CHECKING"
    "CLASS-ATTRIBUTES"
    "CLASS-CONTROL"
    "CLASS-OBJECT"
    "CLEAR-SELECTION"
    "CLINE"
    "CLINES"
    "CLOB"
    "CLOB-FILE"
    "CLOB-LOCATOR"
    "CLOSE-DISPOSITION" ; Unisys
    "CMP" ; Unisys
    "COERCION"
    "COLORS"
    "COLOUR"
    "COLOURS"
    "COLUMN-COLOR"
    "COLUMN-DIVIDERS"
    "COLUMN-FONT"
    "COLUMN-HEADINGS"
    "COLUMN-PROTECTION"
    "COM-REG"
    "COMBO-BOX"
    "COMMAND-LINE"
    "COMMITMENT"
    "COMP-0"
    "COMP-1"
    "COMP-2"
    "COMP-3"
    "COMP-4"
    "COMP-5"
    "COMP-6"
    "COMP-N"
    "COMP-X"
    "COMPRESSION"
    "COMPUTATIONAL-0"
    "COMPUTATIONAL-1"
    "COMPUTATIONAL-2"
    "COMPUTATIONAL-3"
    "COMPUTATIONAL-4"
    "COMPUTATIONAL-5"
    "COMPUTATIONAL-6"
    "COMPUTATIONAL-N"
    "COMPUTATIONAL-X"
    "CONDITION-VALUE"
    "CONNECT-TIME-LIMIT" ; Unisys
    "CONSOLE"
    "CONSTRAIN"
    "CONSTRAINTS"
    "CONTROL-AREA"
    "CONTROL-POINT" ; Unisys
    "CONTROLS-UNCROPPED"
    "CONVENTION"
    "CONVERSION"
    "CONVERT"
    "COPY-SELECTION"
    "CORE-INDEX"
    "CP" ; Unisys
    "CREATING"
    "CRT-UNDER"
    "CRUNCH" ; Unisys
    "CSIZE"
    "CSP"
    "CURSOR-COL"
    "CURSOR-COLOR"
    "CURSOR-FRAME-WIDTH"
    "CURSOR-ROW"
    "CURSOR-X"
    "CURSOR-Y"
    "CUSTOM-ATTRIBUTE"
    "CUSTOM-PRINT-TEMPLATE"
    "CYL-INDEX"
    "CYL-OVERFLOW"
    "DASHED"
    "DATA-COLUMNS"
    "DATA-TYPES"
    "DATABASE-KEY"
    "DATABASE-KEY-LONG"
    "DATE-ENTRY"
    "DATE-RECORD"
    "DBCLOB"
    "DBCLOB-FILE"
    "DBCLOB-LOCATOR"
    "DBCS"
    "DEBUG"
    "DECIMAL"
    "DEFAULT-BUTTON"
    "DEFAULT-FONT"
    "DEFINITION"
    "DELEGATE-ID"
    "DESTROY"
    "DICTIONARY"
    "DISC"
    "DISJOINING"
    "DISK"
    "DISP"
    "DISPLAY-1"
    "DISPLAY-COLUMNS"
    "DISPLAY-FORMAT"
    "DISPLAY-ST"
    "DIVIDER-COLOR"
    "DIVIDERS"
    "DONT-PARTICIPATE" ; Unisys
    "DOT-DASH"
    "DOTTED"
    "DOUBLE"
    "DRAG-COLOR"
    "DRAW"
    "DROP"
    "DROP-DOWN"
    "DROP-LIST"
    "EBCDIC"
    "ECHO"
    "EGCS"
    "EJECT"
    "ELEMENTARY"
    "EMPTY-CHECK"
    "ENABLED"
    "ENCRYPTION"
    "ENDING"
    "ENGRAVED"
    "ENSURE-VISIBLE"
    "ENTRY-FIELD"
    "ENTRY-REASON"
    "ENUM"
    "ENUM-ID"
    "ENVIRONMENT-NAME"
    "ENVIRONMENT-VALUE"
    "EQUALS"
    "ESCAPE"
    "ESCAPE-BUTTON"
    "EVENT"
    "EVENT-LIST"
    "EVENT-POINTER"
    "EXCEEDS"
    "EXCEPTION-VALUE"
    "EXCESS-3"
    "EXCLUDE-EVENT-LIST"
    "EXCLUSIVE"
    "EXPAND"
    "EXTENDED"
    "EXTENDED-SEARCH"
    "EXTENSION"
    "EXTERNAL-FORM"
    "EXTERNALLY-DESCRIBED-KEY"
    "FH--FCD"
    "FH--KEYDEF"
    "FILE-ID"
    "FILE-LIMIT"
    "FILE-LIMITS"
    "FILE-NAME"
    "FILE-POS"
    "FILL-COLOR"
    "FILL-COLOR2"
    "FILL-PERCENT"
    "FINALLY"
    "FINISH-REASON"
    "FIXED"
    "FIXED-FONT"
    "FIXED-WIDTH"
    "FLAT"
    "FLAT-BUTTONS"
    "FLOAT"
    "FLOATING"
    "FONT"
    "FOREGROUND-COLOUR"
    "FRAME"
    "FRAMED"
    "FULL-HEIGHT"
    "GETTER"
    "GO-BACK"
    "GO-FORWARD"
    "GO-HOME"
    "GO-SEARCH"
    "GRAPHICAL"
    "GRID"
    "GRIP"
    "GROUP-VALUE"
    "HANDLE"
    "HAS-CHILDREN"
    "HEADING-COLOR"
    "HEADING-DIVIDER-COLOR"
    "HEADING-FONT"
    "HEAVY"
    "HEIGHT"
    "HEIGHT-IN-CELLS"
    "HELP-ID"
    "HIDDEN-DATA"
    "HIGH"
    "HIGH-COLOR"
    "HORIZONTAL"
    "HOT-TRACK"
    "HSCROLL"
    "HSCROLL-POS"
    "ICON"
    "ID"
    "IGNORE"
    "INDEPENDENT"
    "INDEXED"
    "INDEXER"
    "INDEXER-ID"
    "INDIC"
    "INDICATOR"
    "INDICATORS"
    "INDIRECT"
    "INHERITING"
    "INQUIRE"
    "INTERRUPT"
    "INSERT"
    "INSERT-ROWS"
    "INSERTION-INDEX"
    "INSTANCE"
    "INTERNAL"
    "INVOKED"
    "ITEM"
    "ITEM-BOLD"
    "ITEM-ID"
    "ITEM-TEXT"
    "ITEM-TO-ADD"
    "ITEM-TO-DELETE"
    "ITEM-TO-EMPTY"
    "ITEM-VALUE"
    "ITERATOR"
    "ITERATOR-ID"
    "JOINED"
    "JOINING"
    "KANJI"
    "KEPT"
    "KEY-YY"
    "KEYBOARD"
    "LABEL-OFFSET"
    "LARGE-FONT"
    "LAST-ROW"
    "LAYOUT-DATA"
    "LAYOUT-MANAGER"
    "LEADING-SHIFT"
    "LEAVE"
    "LEFT-JUSTIFY"
    "LEFT-TEXT"
    "LEFTLINE"
    "LENGTH-CHECK"
    "LENGTH OF"
    "LIN"
    "LINES-AT-ROOT"
    "LINK"
    "LIST"
    "LIST-BOX"
    "LM-RESIZE"
    "LANGUAGE"
    "LOCAL" ; Unisys
    "LOCKING"
    "LONG-DATE"
    "LONG-VARBINARY"
    "LONG-VARCHAR"
    "LOW"
    "LOW-COLOR"
    "LOWER"
    "LOWER-BOUND" ; Unisys
    "LOWER-BOUNDS" ; Unisys
    "LOWERED"
    "MASS-UPDATE"
    "MASTER-INDEX"
    "MAX-HEIGHT"
    "MAX-LINES"
    "MAX-PROGRESS"
    "MAX-SIZE"
    "MAX-TEXT"
    "MAX-VAL"
    "MAX-WIDTH"
    "MDI-CHILD"
    "MDI-FRAME"
    "MEDIUM-FONT"
    "MENU"
    "MESSAGES"
    "METACLASS"
    "MIN-HEIGHT"
    "MIN-LINES"
    "MIN-SIZE"
    "MIN-VAL"
    "MIN-WIDTH"
    "MMDDYYYY" ; Unisys
    "MODAL"
    "MODELESS"
    "MODIFIED"
    "MONITOR-POINTER"
    "MORE-DATA" ; Unisys
    "MORE-LABELS"
    "MULTILINE"
    "MUTEX-POINTER"
    "MYJOB" ; Unisys
    "MYSELF" ; Unisys
    "NAME"
    "NAMED"
    "NAVIGATE-URL"
    "NCHAR"
    "NET-EVENT-LIST"
    "NEW"
    "NEWABLE"
    "NEXT-ITEM"
    "NO-AUTO-DEFAULT"
    "NO-AUTOSEL"
    "NO-BOX"
    "NO-CELL-DRAG"
    "NO-CLOSE"
    "NO-DIVIDERS"
    "NO-ECHO"
    "NO-F4"
    "NO-FOCUS"
    "NO-GROUP-TAB"
    "NO-KEY-LETTER"
    "NO-SEARCH"
    "NO-TAB"
    "NO-UPDOWN"
    "NOMINAL"
    "NOTIFY"
    "NOTIFY-CHANGE"
    "NOTIFY-DBLCLICK"
    "NOTIFY-SELCHANGE"
    "NSTD-REELS"
    "NUM-COL-HEADINGS"
    "NUM-ROW-HEADINGS"
    "NUM-ROWS"
    "NUMERIC-DATE" ; Unisys
    "NUMERIC-FILL"
    "NUMERIC-TIME" ; Unisys
    "O-FILL"
    "OBJECT-ID"
    "OBJECT-STORAGE"
    "OC" ; Unisys
    "ODT-INPUT-PRESENT" ; Unisys
    "OK-BUTTON"
    "OOSTACKPTR"
    "OPERATOR"
    "OPERATOR-ID"
    "OTHERWISE"
    "OVERLAP-LEFT"
    "OVERLAP-TOP"
    "OVERLAPPED"
    "OVERLINE"
    "OWN" ; Unisys
    "PAGE-SETUP"
    "PAGE-SIZE"
    "PAGED"
    "PANEL-INDEX"
    "PANEL-STYLE"
    "PANEL-TEXT"
    "PANEL-WIDTHS"
    "PARAMS"
    "PARENT"
    "PARSE"
    "PARTIAL"
    "PARTICIPATE" ; Unisys
    "PASSWORD"
    "PC" ; Unisys
    "PERMANENT"
    "PIXEL"
    "PIXELS"
    "PLACEMENT"
    "POP-UP"
    "POSITION-SHIFT"
    "POSITIONING"
    "PREFIXING"
    "PRINT"
    "PRINT-CONTROL"
    "PRINT-NO-PROMPT"
    "PRINT-PREVIEW"
    "PRINT-SWITCH"
    "PRINTER"
    "PRINTER-1"
    "PRIOR"
    "PRIORITY"
    "PRIVATE"
    "PROCEDURE-POINTER"
    "PROCESSING"
    "PROGRESS"
    "PROMPT"
    "PROPERTIES"
    "PROPERTY-ID"
    "PROPERTY-VALUE"
    "PROTECTED"
    "PUBLIC"
    "PUSH-BUTTON"
    "QUERY-INDEX"
    "RADIO-BUTTON"
    "RAISED"
    "READ-OK" ; Unisys
    "READ-ONLY"
    "READING"
    "READY"
    "REAL" ; Unisys
    "RECORD-DATA"
    "RECORD-OVERFLOW"
    "RECORD-TO-ADD"
    "RECORD-TO-DELETE"
    "RECORDING"
    "REDEFINE"
    "REDEFINITION"
    "REF" ; Unisys
    "REFRESH"
    "REGION-COLOR"
    "REJECT-OPEN"
    "RELOAD"
    "REMARKS"
    "REORG-CRITERIA"
    "REPEATED"
    "REREAD"
    "RESET"
    "RESET-GRID"
    "RESET-LIST"
    "RESET-TABS"
    "RESIDENT"
    "RESIZABLE"
    "RESTRICTED"
    "RESULT-SET-LOCATOR"
    "RETURN-CODE"
    "RIGHT-ALIGN"
    "RIGHT-JUSTIFY"
    "RIMMED"
    "ROLLING"
    "ROW-COLOR"
    "ROW-COLOR-PATTERN"
    "ROW-DIVIDERS"
    "ROW-FONT"
    "ROW-HEADINGS"
    "ROW-PROTECTION"
    "ROWID"
    "S01"
    "S02"
    "S03"
    "S04"
    "S05"
    "SAVE-AS"
    "SAVE-AS-NO-PROMPT"
    "SCROLL"
    "SCROLL-BAR"
    "SEARCH-OPTIONS"
    "SEARCH-TEXT"
    "SELECT-ALL"
    "SELECTION-INDEX"
    "SELECTION-TEXT"
    "SELECTIVE"
    "SELF-ACT"
    "SELFCLASS"
    "SEMAPHORE-POINTER"
    "SEPARATION"
    "SETTER"
    "SHADING"
    "SHADOW"
    "SHIFT-IN"
    "SHIFT-OUT"
    "SHORT-DATE"
    "SHOW-LINES"
    "SHOW-NONE"
    "SHOW-SEL-ALWAYS"
    ;; SIGN is treated as an intrinsic function.
    "SIGNED-INT"
    "SIGNED-LONG"
    "SIGNED-SHORT"
    "SKIP1"
    "SKIP2"
    "SKIP3"
    "SMALL-FONT"
    "SORT-CONTROL"
    "SORT-CORE-SIZE"
    "SORT-FILE-SIZE"
    "SORT-MESSAGE"
    "SORT-MODE-SIZE"
    "SORT-OPTION"
    "SORT-ORDER"
    "SORT-RETURN"
    "SORT-TAPE"
    "SORT-TAPES"
    "SPACE-FILL"
    "SPINNER"
    "SQL"
    "SQUARE"
    "STANDARD-3"
    "START-X"
    "START-Y"
    "STARTING"
    "STATIC"
    "STATIC-LIST"
    "STATIONLIST"
    "STATUS-BAR"
    "STATUS-TEXT"
    "STDCALL"
    "STOP-BROWSER"
    "STYLE"
    "SUBFILE"
    "SUBWINDOW"
    "SUFFIXING"
    ;; SUM is an intrinsic function.
    "SW0"
    "SW1"
    "SW2"
    "SW3"
    "SW4"
    "SW5"
    "SW6"
    "SW7"
    "SW8"
    "SW9"
    "SW10"
    "SW11"
    "SW12"
    "SW13"
    "SW14"
    "SW15"
    "SWITCH-0"
    "SWITCH-1"
    "SWITCH-2"
    "SWITCH-3"
    "SWITCH-4"
    "SWITCH-5"
    "SWITCH-6"
    "SWITCH-7"
    "SWITCH-8"
    "SWITCH-9"
    "SWITCH-10"
    "SWITCH-11"
    "SWITCH-12"
    "SWITCH-13"
    "SWITCH-14"
    "SWITCH-15"
    "SYSIN"
    "SYSIPT"
    "SYSLST"
    "SYSOUT"
    "SYSPCH"
    "SYSPUNCH"
    "SYSTEM"
    "SYSTEM-INFO"
    "TAB"
    "TAB-CONTROL"
    "TAB-TO-ADD"
    "TAB-TO-DELETE"
    "TAG-KEY" ; Unisys
    "TAG-SEARCH" ; Unisys
    "TALLY"
    "TAPES"
    "TASK"
    "TEMPORARY"
    "TERMINAL-INFO"
    "TERMINATION-VALUE"
    "THREAD"
    "THREAD-LOCAL"
    "THREAD-LOCAL-STORAGE"
    "THREAD-POINTER"
    "THUMB-POSITION"
    "TILED-HEADINGS"
    "TIME-OF-DAY"
    "TIME-OUT"
    "TIME-RECORD"
    "TIMEOUT"
    "TIMER" ; Unisys
    "TIMESTAMP"
    "TIMESTAMP-OFFSET"
    "TIMESTAMP-OFFSET-RECORD"
    "TIMESTAMP-RECORD"
    "TITLE"
    "TITLE-BAR"
    "TITLE-POSITION"
    "TODAYS-DATE"
    "TODAYS-NAME"
    "TOOL-BAR"
    "TOTALED"
    "TOTALING"
    "TRACE"
    "TRACK-AREA"
    "TRACK-LIMIT"
    "TRACK-THUMB"
    "TRACKS"
    "TRADITIONAL-FONT"
    "TRAILING-SHIFT"
    "TRAILING-SIGN"
    "TRANSACTION"
    "TRANSPARENT"
    "TRANSPARENT-COLOR"
    "TREE-VIEW"
    "UNDERLINED"
    "UNEQUAL"
    "UNFRAMED"
    "UNITS"
    "UNSIGNED-INT"
    "UNSIGNED-LONG"
    "UNSIGNED-SHORT"
    "UNSORTED"
    "UPDATE"
    "UPPER"
    "UPSI-0"
    "UPSI-1"
    "UPSI-2"
    "UPSI-3"
    "UPSI-4"
    "UPSI-5"
    "UPSI-6"
    "UPSI-7"
    "URGENT"
    "USE-ALT"
    "USE-RETURN"
    "USE-TAB"
    "USER"
    "USER-COLORS"
    "USER-GRAY"
    "USER-WHITE"
    "VA" ; Unisys
    "VALUE-FORMAT"
    "VALUETYPE"
    "VALUETYPE-ID"
    "VARBINARY"
    "VARIABLE"
    "VARIANT"
    "VERTICAL"
    "VERY-HEAVY"
    "VIRTUAL-WIDTH"
    "VISIBLE"
    "VPADDING"
    "VSCROLL"
    "VSCROLL-BAR"
    "VSCROLL-POS"
    "VTOP"
    "WEB-BROWSER"
    "WHERE"
    "WIDTH"
    "WIDTH-IN-CELLS"
    "WINDOW"
    "WRAP"
    "WRITE-ONLY"
    "WRITE-VERIFY"
    "WRITING"
    "XML"
    "XML-CODE"
    "XML-EVENT"
    "XML-NTEXT"
    "XML-TEXT"
    "YIELDING"
    "ZERO-FILL"))

(defvar cobol-keywords
  (append cobol-keywords-2014
          cobol-removed-keywords-2002
          cobol-removed-keywords-2014
          cobol-keywords-finalizer-tr
          cobol-keywords-xml-tr
          cobol-keywords-extensions
          cobol-scope-terminators
          cobol-removed-scope-terminators-2014)
  "List of COBOL keywords.")

(defconst cobol-context-sensitive-keywords-2002
  '("ARITHMETIC"
    "ATTRIBUTE"
    "AUTO"
    "AUTOMATIC"
    "BACKGROUND-COLOR"
    "BELL"
    "BLINK"
    "BYTE-LENGTH"
    "CENTER"
    "CLASSIFICATION"
    "CYCLE"
    "EC-ALL"
    "EC-ARGUMENT"
    "EC-ARGUMENT-FUNCTION"
    "EC-ARGUMENT-IMP"
    "EC-BOUND"
    "EC-BOUND-IMP"
    "EC-BOUND-ODO"
    "EC-BOUND-OVERFLOW"
    "EC-BOUND-PTR"
    "EC-BOUND-REF-MOD"
    "EC-BOUND-SET"
    "EC-BOUND-SUBSCRIPT"
    "EC-BOUND-TABLE-LIMIT"
    "EC-DATA"
    "EC-DATA-CONVERSION"
    "EC-DATA-IMP"
    "EC-DATA-INCOMPATIBLE"
    "EC-DATA-INTEGRITY"
    "EC-DATA-PTR-NULL"
    "EC-FLOW"
    "EC-FLOW-GLOBAL-EXIT"
    "EC-FLOW-GLOBAL-GOBACK"
    "EC-FLOW-IMP"
    "EC-FLOW-RELEASE"
    "EC-FLOW-REPORT"
    "EC-FLOW-RETURN"
    "EC-FLOW-SEARCH"
    "EC-FLOW-USE"
    "EC-FUNCTION"
    "EC-FUNCTION-PTR-INVALID"
    "EC-FUNCTION-PTR-NULL"
    "EC-I-O"
    "EC-I-O-AT-END"
    "EC-I-O-EOP"
    "EC-I-O-EOP-OVERFLOW"
    "EC-I-O-FILE-SHARING"
    "EC-I-O-IMP"
    "EC-I-O-INVALID-KEY"
    "EC-I-O-LINAGE"
    "EC-I-O-LOGIC-ERROR"
    "EC-I-O-PERMANENT-ERROR"
    "EC-I-O-RECORD-OPERATION"
    "EC-IMP"
    ;; EC-IMP-suffix is matched separately by
    ;; cobol-implementor-user-exception-re.
    "EC-LOCALE"
    "EC-LOCALE-IMP"
    "EC-LOCALE-INCOMPATIBLE"
    "EC-LOCALE-INVALID"
    "EC-LOCALE-INVALID-PTR"
    "EC-LOCALE-MISSING"
    "EC-LOCALE-SIZE"
    "EC-OO"
    "EC-OO-CONFORMANCE"
    "EC-OO-EXCEPTION"
    "EC-OO-IMP"
    "EC-OO-METHOD"
    "EC-OO-NULL"
    "EC-OO-RESOURCE"
    "EC-OO-UNIVERSAL"
    "EC-ORDER"
    "EC-ORDER-IMP"
    "EC-ORDER-NOT-SUPPORTED"
    "EC-OVERFLOW"
    "EC-OVERFLOW-IMP"
    "EC-OVERFLOW-STRING"
    "EC-OVERFLOW-UNSTRING"
    "EC-PROGRAM"
    "EC-PROGRAM-ARG-MISMATCH"
    "EC-PROGRAM-ARG-OMITTED"
    "EC-PROGRAM-CANCEL-ACTIVE"
    "EC-PROGRAM-IMP"
    "EC-PROGRAM-NOT-FOUND"
    "EC-PROGRAM-PTR-NULL"
    "EC-PROGRAM-RECURSIVE-CALL"
    "EC-PROGRAM-RESOURCES"
    "EC-RAISING"
    "EC-RAISING-IMP"
    "EC-RAISING-NOT-SPECIFIED"
    "EC-RANGE"
    "EC-RANGE-IMP"
    "EC-RANGE-INDEX"
    "EC-RANGE-INSPECT-SIZE"
    "EC-RANGE-INVALID"
    "EC-RANGE-PERFORM-VARYING"
    "EC-RANGE-PTR"
    "EC-RANGE-SEARCH-INDEX"
    "EC-RANGE-SEARCH-NO-MATCH"
    "EC-REPORT"
    "EC-REPORT-ACTIVE"
    "EC-REPORT-COLUMN-OVERLAP"
    "EC-REPORT-FILE-MODE"
    "EC-REPORT-IMP"
    "EC-REPORT-INACTIVE"
    "EC-REPORT-LINE-OVERLAP"
    "EC-REPORT-NOT-TERMINATED"
    "EC-REPORT-PAGE-LIMIT"
    "EC-REPORT-PAGE-WIDTH"
    "EC-REPORT-SUM-SIZE"
    "EC-REPORT-VARYING"
    "EC-SCREEN"
    "EC-SCREEN-FIELD-OVERLAP"
    "EC-SCREEN-IMP"
    "EC-SCREEN-ITEM-TRUNCATED"
    "EC-SCREEN-LINE-NUMBER"
    "EC-SCREEN-STARTING-COLUMN"
    "EC-SIZE"
    "EC-SIZE-ADDRESS"
    "EC-SIZE-EXPONENTIATION"
    "EC-SIZE-IMP"
    "EC-SIZE-OVERFLOW"
    "EC-SIZE-TRUNCATION"
    "EC-SIZE-UNDERFLOW"
    "EC-SIZE-ZERO-DIVIDE"
    "EC-SORT-MERGE"
    "EC-SORT-MERGE-ACTIVE"
    "EC-SORT-MERGE-FILE-OPEN"
    "EC-SORT-MERGE-IMP"
    "EC-SORT-MERGE-RELEASE"
    "EC-SORT-MERGE-RETURN"
    "EC-SORT-MERGE-SEQUENCE"
    "EC-STORAGE"
    "EC-STORAGE-IMP"
    "EC-STORAGE-NOT-ALLOC"
    "EC-STORAGE-NOT-AVAIL"
    "EC-USER"
    ;; EC-USER-suffix is matched separately by
    ;; cobol-implementor-user-exception-re.
    "EC-VALIDATE"
    "EC-VALIDATE-CONTENT"
    "EC-VALIDATE-FORMAT"
    "EC-VALIDATE-IMP"
    "EC-VALIDATE-RELATION"
    "EC-VALIDATE-VARYING"
    "EOL"
    "EOS"
    "ENTRY-CONVENTION"
    "ERASE"
    "EXPANDS"
    "FOREGROUND-COLOR"
    "FOREVER"
    "FULL"
    "HIGHLIGHT"
    "IGNORING"
    "IMPLEMENTS"
    "INITIALIZED"
    "INTRINSIC"
    "LC_ALL"
    "LC_COLLATE"
    "LC_CTYPE"
    "LC_MESSAGES"
    "LC_MONETARY"
    "LC_NUMERIC"
    "LC_TIME"
    "LOWLIGHT"
    "MANUAL"
    "MULTIPLE" ; <= COBOL-74
    "NEGATIVE-INFINITY"
    "NONE"
    "NORMAL"
    "NUMBERS"
    "ONLY"
    "PARAGRAPH"
    "POSITIVE-INFINITY"
    "PREVIOUS"
    "RECURSIVE"
    "RELATION"
    "REQUIRED"
    "REVERSE-VIDEO"
    "SECONDS"
    "SECURE"
    "STATEMENT"
    "STEP"
    "STRONG"
    "SYMBOL"
    "UCS-4"
    "UNDERLINE"
    "UNSIGNED"
    "UTF-8"
    "UTF-16"
    ;; XML is treated as a reserved word per IBM implementations.
    "YYYYDDD"
    "YYYYMMDD"))

(defconst cobol-context-sensitive-keywords-finalizer-tr
  '("EC-OO-FINALIZABLE"
    "FINALIZER"))

(defconst cobol-context-sensitive-keywords-xml-tr
  '("CHECK"
    "DISCARD"
    "DOCUMENTATION"
    "DTD"
    "EC-DATA-INFINITY"
    "EC-DATA-NEGATIVE-INFINITY"
    "EC-DATA-NOT-A-NUMBER"
    "EC-XML"
    "EC-XML-CODESET"
    "EC-XML-CODESET-CONVERSION"
    "EC-XML-COUNT"
    "EC-XML-DOCUMENT-TYPE"
    "EC-XML-IMPLICIT-CLOSE"
    "EC-XML-INVALID"
    "EC-XML-NAMESPACE"
    "EC-XML-STACKED-OPEN"
    "EC-XML-RANGE"
    "ELEMENT"
    "NAMESPACE"
    "RAW"
    "SCHEMA"
    "STACK"
    "VALIDITY"))

(defconst cobol-context-sensitive-keywords-2014
  (append cobol-context-sensitive-keywords-2002
          '("AWAY-FROM-ZERO"
            "BINARY-ENCODING"
            "CAPACITY"
            "DECIMAL-ENCODING"
            "EC-FUNCTION-ARG-OMITTED"
            "EC-FUNCTION-NOT-FOUND"
            "EC-OO-ARG-OMITTED"
            "FLOAT-BINARY"
            "FLOAT-DECIMAL"
            "HIGH-ORDER-LEFT"
            "HIGH-ORDER-RIGHT"
            "INTERMEDIATE"
            "NEAREST-AWAY-FROM-ZERO"
            "NEAREST-EVEN-INTERMEDIATE"
            "NEAREST-TOWARD-ZERO"
            "PREFIXED"
            "PROHIBITED"
            "ROUNDING"
            "SHORT"
            "SIGNED"
            "STANDARD-BINARY"
            "STANDARD-DECIMAL"
            "TOWARD-GREATER"
            "TOWARD-LESSER"
            "TRUNCATION")))

(defconst cobol-context-sensitive-extensions
  '("TRUNCATED" ; Unisys
    ))

(defvar cobol-context-sensitive-keywords
  (append cobol-context-sensitive-keywords-2014
          cobol-context-sensitive-keywords-finalizer-tr
          cobol-context-sensitive-keywords-xml-tr
          cobol-context-sensitive-extensions)
  "List of context-sensitive COBOL keywords.")

(defconst cobol-intrinsics-85
  '("ACOS"
    "ANNUITY"
    "ASIN"
    "ATAN"
    ;; BYTE-LENGTH is treated as a context-sensitive word.
    "CHAR"
    "COS"
    "CONCATENATE"
    "CURRENT-DATE"
    "DATE-OF-INTEGER"
    "DAY-OF-INTEGER"
    "FACTORIAL"
    "INTEGER"
    "INTEGER-OF-DATE"
    "INTEGER-OF-DAY"
    "INTEGER-PART"
    "LENGTH"
    "LOG"
    "LOG10"
    "LOWER-CASE"
    "MAX"
    "MEAN"
    "MEDIAN"
    "MIDRANGE"
    "MIN"
    "MOD"
    "NUMVAL"
    "NUMVAL-C"
    "ORD"
    "ORD-MAX"
    "ORD-MIN"
    "PRESENT-VALUE"
    ;; RANDOM is treated as a keyword
    "RANGE"
    "REM"
    "REVERSE"
    "SIGN" ; Keyword <= COBOL-74
    "SIN"
    "SQRT"
    "STANDARD-DEVIATION"
    "SUM" ; Keyword <= COBOL-74
    "TAN"
    "UPPER-CASE"
    "VARIANCE"
    "WHEN-COMPILED"))

(defconst cobol-intrinsics-2002
  (append cobol-intrinsics-85
          '("ABS"
            "BOOLEAN-OF-INTEGER"
            "CHAR-NATIONAL"
            "DATE-TO-YYYYMMDD"
            "DAY-TO-YYYYDDD"
            "DISPLAY-OF"
            "E"
            "EXCEPTION-FILE"
            "EXCEPTION-FILE-N"
            "EXCEPTION-LOCATION"
            "EXCEPTION-LOCATION-N"
            "EXCEPTION-STATEMENT"
            "EXCEPTION-STATUS"
            "EXP"
            "EXP10"
            "FRACTION-PART"
            "HIGHEST-ALGEBRAIC"
            "INTEGER-OF-BOOLEAN"
            "LOCALE-COMPARE"
            "LOCALE-DATE"
            "LOCALE-TIME"
            "LOWEST-ALGEBRAIC"
            "NATIONAL-OF"
            "NUMVAL-F"
            "PI"
            "STANDARD-COMPARE"
            "TEST-DATE-YYYYMMDD"
            "TEST-DAY-YYYYDDD"
            "TEST-NUMVAL"
            "TEST-NUMVAL-C"
            "TEST-NUMVAL-F"
            "YEAR-TO-YYYY")))

(defconst cobol-intrinsics-2014
  (append cobol-intrinsics-2002
          '("COMBINED-DATETIME"
            "FORMATTED-CURRENT-DATE"
            "FORMATTED-DATE"
            "FORMATTED-DATETIME"
            "FORMATTED-TIME"
            "INTEGER-OF-FORMATTED-DATE"
            "LOCALE-TIME-FROM-SECONDS"
            "SECONDS-FROM-FORMATTED-TIME"
            "SECONDS-PAST-MIDNIGHT"
            "TEST-FORMATTED-DATETIME"
            "TRIM")))

(defconst cobol-intrinsics-extensions
  '("ADDR"
    "CURRENCY-SYMBOL"
    "LENGTH-AN"
    "MODULE-CALLER-ID"
    "MODULE-DATE"
    "MODULE-FORMATTED-DATE"
    "MODULE-ID"
    "MODULE-PATH"
    "MODULE-SOURCE"
    "MONETARY-DECIMAL-POINT"
    "MONETARY-THOUSANDS-SEPARATOR"
    "NUMERIC-DECIMAL-POINT"
    "NUMERIC-THOUSANDS-SEPARATOR"
    "STORED-CHAR-LENGTH"
    "SUBSTITUTE"
    "SUBSTITUTE-CASE"
    "ULENGTH"
    "UPOS"
    "USUBSTR"
    "USUPPLEMENTARY"
    "UVALID"
    "UWIDTH"))

(defvar cobol-intrinsics
  (append cobol-intrinsics-2014
          cobol-intrinsics-extensions)
  "List of COBOL standard functions.")

(defconst cobol-symbolic-literals-74
  '("HIGH-VALUE"
    "HIGH-VALUES"
    "LOW-VALUE"
    "LOW-VALUES"
    "QUOTE"
    "QUOTES"
    "SPACE"
    "SPACES"
    "ZERO"
    "ZEROES"
    "ZEROS"))

(defconst cobol-symbolic-literals-85
  cobol-symbolic-literals-74)

(defconst cobol-symbolic-literals-2002
  (append cobol-symbolic-literals-85
          '("NULL"
            "SELF"
            "SUPER")))

(defconst cobol-symbolic-literals-2014
  cobol-symbolic-literals-2002)

(defconst cobol-symbolic-literals-extensions
  '("NULLS"))

(defvar cobol-symbolic-literals
  (append cobol-symbolic-literals-2014
          cobol-symbolic-literals-extensions)
  "List of COBOL symbolic literals.")

(defvar gnucobol-mode-map
  (let ((map (make-keymap)))
    (define-key map "\C-j" 'newline-and-indent)
    map)
  "Keymap for GNUCOBOL major mode.")

(add-to-list 'auto-mode-alist '("\\.cob\\'" . gnucobol-mode))

(defvar cobol-mode-syntax-table
  (let ((st (make-syntax-table)))
    (modify-syntax-entry ?-  "w"   st)
    (modify-syntax-entry ?_  "w"   st)
    (modify-syntax-entry ?*  ". 1" st)
    (modify-syntax-entry ?>  "w 2" st)
    (modify-syntax-entry ?\\ "."   st)
    (modify-syntax-entry ?'  "\""  st)
    (modify-syntax-entry ?\" "\""  st)
    (modify-syntax-entry ?\n ">"   st)
    st))


(defvar cobol-font-lock-defaults
  `((;; Directives
     ( ,(concat cobol--directive-indicator-re
                "\\(" (regexp-opt cobol-directives) "\\>\\)")
       . font-lock-preprocessor-face)
     ( ,cobol--mf-compiler-directive-re . font-lock-preprocessor-face)

     ;; TO-DO: Highlight reserved words in directives as reserved words

     ;; Standard language features.
     ( ,(regexp-opt cobol-verbs 'words) . 'cobol-verb)
     ( ,(regexp-opt cobol-keywords 'words) . font-lock-keyword-face)
     ( ,(regexp-opt cobol-context-sensitive-keywords 'words)
       . 'cobol-context-sensitive)
     ( ,cobol--implementer-user-exception-re . 'cobol-context-sensitive)
     ( ,(regexp-opt cobol-intrinsics 'words) . font-lock-builtin-face)

     ;; Constants
     ( ,(regexp-opt cobol-symbolic-literals 'words) . font-lock-constant-face)
     ( ,cobol--standard-constant-re
       (1 'font-lock-constant-face))
     ( ,cobol--mf-constant-re
       (1 'font-lock-constant-face))
     ( ,cobol--define-directive-re
       (1 'font-lock-constant-face))

     ;; PIC Type
     ( ,cobol--pic-type-re
       (3 'font-lock-type-face))

     ;; Functions
     ( ,cobol--function-call-re
       (1 'font-lock-function-name-face))

     ;; REPOSITORY clauses
     ( ,cobol--repository-function-type-clause-re
       (2 'font-lock-function-name-face))
     ( ,cobol--repository-type-type-clause-re
       (2 'font-lock-type-face))

     ;; File declarations
     ( ,cobol--select-file-re
       (2 'font-lock-type-face))

     ;; File/Report/Sort record associations
     ( ,cobol--record-descriptor-re
       (1 'font-lock-type-face))

     ;; Typedef
     ( ,cobol--typedef-definition-re
       (1 'font-lock-type-face))

     ;; Variables
     ( ,cobol--variable-declaration-re
       (1 'font-lock-variable-name-face))
     ( ,cobol--mf-declare-variable-re
       (1 'font-lock-variable-name-face))

     ;; Construct IDs
     ( ,cobol--function-id-name-re
       (1 'font-lock-function-name-face))
     ( ,cobol--type-id-name-re
       (1 'font-lock-type-face))
     ( ,cobol--mf-property-id-name-re
       (1 'font-lock-variable-name-face)
       (2 'font-lock-type-face))

     ;; Construct end markers
     ( ,cobol--function-end-marker-re
       (1 'font-lock-function-name-face))
     ( ,cobol--type-end-marker-re
       (1 'font-lock-type-face))

     ;; Invoked classes
     ( ,cobol--mf-invoked-class-re
       (1 'font-lock-type-face))

     ;; Procedures
     ( ,cobol--procedure-re
       (1 'font-lock-function-name-face))

     ( ,cobol--string-literal-type-re
       (1 'font-lock-string-face)))
    nil
    t
    nil
    nil))

(define-derived-mode gnucobol-mode prog-mode "GNUCOBOL"
  "COBOL mode is a major mode for handling COBOL files."
  :group 'gnucobol

  (set (make-local-variable 'font-lock-defaults) cobol-font-lock-defaults)

  ;;  (when cobol-tab-width (set (make-local-variable 'tab-width) cobol-tab-width))

  ;; (set (make-local-variable 'indent-tabs-mode) nil)

  (set (make-local-variable 'comment-start-skip) "\\(^.\\{6\\}\\*\\|\\*>\\)\\s-* *")
  (set (make-local-variable 'comment-start) "*>")
  (set (make-local-variable 'comment-end) "")

  ;;  (set (make-local-variable 'syntax-propertize-function)  #'cobol--syntax-propertize-function)

  (seyt (make-local-variable 'column-number-mode) t)

  ;;  (set (make-local-variable 'indent-line-function) #'cobol-indent-line)

  ;; Auto complete mode
  (set (make-local-variable 'ac-ignore-case) t)
  )

(provide 'gnucobol-mode)
;;; gnucobol-mode.el ends here


